### ISSUE TITLE
Smaller tasks?

### ISSUE THREAD

**Issue by Ukundji** [MRVDH/mapping-north-korea#61]
I think that the size of the tasks as thzey are right now is much too big. They include almost 40 square kilometers while one square kilometer in a relatuively densely populated county like North Korea (with poor OSM coverage so far) would already be a challenge.
My radical idea/suggestion would be to split all the orginal tasks in 32 parts. It is always good and motivating for a mapper if he/she has the chance to finish a task.

**Comment by MRVDH** [comment]
Moved to #52 (main discussion)
